#baseURL = "http://localhost:1313"
#baseURL = "https://vedicastrology-amp.netlify.app/"
baseURL = "https://stevehora.com"

languageCode = "en-us"
title = "Hora Vedic Astrology by Steve for Birth Chart Wealth Predictions"
theme="steve"
paginate = 5
canonifyurls = true
summaryLength = 24

[permalinks]
    post = '/:year/:month/:slug/' # Wordpress style
	
# Define the default author
[author]
    name = "Steve Hora"
	email = "steve@stevehora.com"
    bio = "Vedic Astrologer"
    location = "SFO, USA"
    website = "https://stevehora.com"
    thumbnail = "/steve-hora.png"
    facebook = 'https://www.facebook.com/vedicastrology123' # Author's Facebook page
    twitter = '@AstrologyOrbit'

[social]
    facebook = 'https://www.facebook.com/vedicastrology123' # Site's Facebook page
    facebook_admin = 'https://www.facebook.com/vedicastrology123'
    twitter = '@AstrologyOrbit'
	
[params]
  copyright = "Copyright 2014 stevehora.com - All rights reserved - "
  description = "Vedic Astrology by Steve Hora accurate prediction from Birth Chart for Health Wealth Happiness Destiny Fame Success. Mantra Solution Consultation Advice."
  terms = "Terms, Privacy"
  refund = "Refund Policy"
  information = "Your Destiny Your Success"
  cover = "/images/vedic-astrology.gif" # Homepage cover
  cover_sizes = [480, 360]
  #https://kapwi.ng/c/32p9SwRr
  logo = "shri-chakra.png"
  publisherLogoHeight = 60
  publisherLogoWidth = 60
  metadescription = "Hora Vedic Astrology by Steve Hora"
  author = "Steve Hora"
  authorname = "Steve Hora"
  #authorlocation = "SFO, USA"
  #authorwebsite = "https://stevehora.com"
  #authorbio= "Vedic Astrology Expert"
  address = "Chennai, India and SFO, USA"
  organizationName = "stevehora.com"
  breadcrumbsOnPath = true
  locale = "en_US"
  alternatePageName = "Hora Vedic Astrology by Steve"
  # Organization
    socialProfiles = ""
    organizationLogo = "images/shrichakra.png"
    organizationAddress = "SFO, USA"
# Breadcrumb

# Default schema type
    defaultSchema = "article"
 
  mobile = "[Telegram Chat](/articles/telegram/)"
  #mobile1 = "[Chat group](https://chat?Hdj8MZOaSFnKlX43JBebvN)"
  keywords = "Hora, Vedic Astrology , Birth Chart , Steve, Advice, Wealth, Matrimony matching, love compatibility, 27 nakshatras, 20 divisional charts, dhoni famous horoscope, forecast, name, vedas , Calculate your Vedic Astrology Chart , Jyotish , About , Astrology Chat , Contact us , Quora Question and Answers , Predictions, ashtakavarga, astrology temple, august 2020, ayanamsa, bhrigu bindu, birth chart, brave india, case studies, china, coronavirus, dasha, gann w d, george floyd, graha, guru budha, guru dakshina, jaimini, janma nakshatra, karana, karma and astrology, mahatma gandhi, marriage compatibility, nadi astrology, nakshatras, nava grahas, navamsa makara, new world order, privacy, pushya paksha ayanamsa, quora q2a, quora q2a1, rashi sign, rashi, secrets of astrology, secrets of varma, secrets of vedic astrology, stevehora, telegram, tithi information, usa corona, vedic astrology books, vedic astrology meaning, vedic astrology software, vedic astrology tamil"

  newkeys = [ "Hora", "Vedic Astrology" , "Birth Chart" , "Steve", "Advice", "Wealth", "Matrimony matching", "love compatibility", "27 nakshatras", "20 divisional charts", "dhoni famous horoscope", "forecast", "name", "vedas", "Calculate your Vedic Astrology Chart" , "Jyotish" , "About" , "Astrology Chat" , "Contact us" , "Quora Question and Answers" , "Predictions","ashtakavarga","astrology temple","august 2020","ayanamsa","bhrigu bindu","birth chart","brave india","case studies","china","coronavirus","dasha","gann w d","george floyd","graha","guru budha","guru dakshina","jaimini","janma nakshatra","karana","karma and astrology","mahatma gandhi","marriage compatibility","nadi astrology","nakshatras","nava grahas","navamsa makara","new world order","privacy","pushya paksha ayanamsa","quora q2a","quora q2a1","rashi sign","rashi","secrets of astrology","secrets of varma","secrets of vedic astrology","stevehora","telegram","tithi information","usa corona","vedic astrology books","vedic astrology meaning","vedic astrology software","vedic astrology tamil"]


  # Social links on the homepage
  #RSSLink = "http://feeds.feedburner.com/..."
  facebookName = 'vedicastrology123'
  twitterName = '@AstrologyOrbit'
  #instagramName = 'https://www.facebook.com/vedicastrology123'
  #pinterestName = 'https://www.facebook.com/vedicastrology123'
  linkedinName = 'steve-hora-vedic-astrologer'
  email = 'steve@stevehora.com'
  
  themeColor = "green" # Browser bar color
  googleanalytics = "UA-1341906-9"
  adsensepublisher = ""
  ampElements = ["amp-font", "amp-accordion","amp-analytics", "amp-sidebar", "amp-social-share", "amp-carousel","amp-iframe", "amp-position-observer","amp-animation"] # AMP elements loaded on every page

#"amp-user-notification","amp-ad", ,"amp-mustache","amp-bind", "amp-form","amp-list"

[params.structured]
	type = ["Article", "Videos", "Product"]

[params.article.image]
    src = "images/vaashicon.png"
	author = "Steve Hora"
	height = 60
	width = 60

  [params.share]
    twitter = true
    gplus = false
    pinterest = false
    facebook = true
	linkedin = true

[params.favicon]
    manifest = "manifest.json"
    basename = "favicon"
    ms_tilecolor = "#FFFFFF"
    icon = [16, 32, 96, 192]
    apple_touch = [57, 60, 72, 76, 114, 120, 144, 152, 180]
    ms = [144]
    ms_config = "browserconfig.xml"

[[menu.main]]
    name = 'Home'
    weight = 1
    url = '/'

[[menu.main]]
    name = 'Steve Hora'
    weight = 2
    url = '/steve-hora/'

[[menu.main]]
    name = 'Free Vedic...'
    weight = 3
    url = '/vedic-chart/'

[[menu.main]]
    name = 'Vedic Astrology Articles'
    weight = 4
    url = '/articles/'
	
[[menu.main]]
    name = 'About Us'
    weight = 5
    url = '/about/'	
	
[[menu.main]]
    name = 'Contact Us'
    weight = 6
    url = '/contact/'	
	
[[menu.main]]
    name = 'Search'
    weight = 7
    url = '/search/'

[mediaTypes]
[mediaTypes."application/opensearchdescription+xml"]
suffixes = ["xml"]

[outputFormats.SearchIndex]
		mediaType = "application/json"
		baseName = "searchindex"
		isPlainText = true
		notAlternative = true

[outputFormats.OpenSearch]
	baseName = "opensearch"
	isHTML = false
	isPlainText = false
	mediaType = "application/opensearchdescription+xml"
	noUgly = true

[outputs]
	home = ["HTML", "RSS", "SearchIndex", "OpenSearch"]

[taxonomies]
  category = "categories"
  tag = "tags"
  keyword = "keywords"