baseURL = "http://localhost:1313"
#baseURL = "https://vedicastrology-amp.netlify.app/"

languageCode = "en-us"
title = "Vedic Astrology"
theme="steve"
paginate = 5
canonifyurls = true

[permalinks]
    post = '/:year/:month/:slug/' # Wordpress style
	
# Define the default author
[author]
    name = "Steve Hora"
    bio = "Vedic Astrologer"
    location = "SFO, USA"
    website = "https://stevehora.com"
    thumbnail = "/stevehora.bmp"
	
[params]
  copyright = "Copyright 2014 stevehora.com - All rights reserved - "
  description = "Steve Hora"
  terms = "Terms, Privacy"
  refund = "Refund Policy"
  information = "Your Destiny Your Success"
  cover = "/images/planets.gif" # Homepage cover
  logo = "images/shrichakra9.png"
  metadescription = "Hora Vedic Astrology by Steve Hora"
  author = "Steve Hora"
  authorname = "Steve Hora"
  #authorlocation = "SFO, USA"
  #authorwebsite = "https://stevehora.com"
  #authorbio= "Vedic Astrology Expert"

  mobile = "[Telegram Chat](/articles/telegram/)"
  #mobile1 = "[Chat group](https://chat?Hdj8MZOaSFnKlX43JBebvN)"

  # Social links on the homepage
  #RSSLink = "http://feeds.feedburner.com/..."
  facebookName = 'vedicastrology123'
  twitterName = '@AstrologyOrbit'
  #instagramName = 'https://www.facebook.com/vedicastrology123'
  #pinterestName = 'https://www.facebook.com/vedicastrology123'
  linkedinName = 'steve-hora-vedic-astrologer'
  email = 'steve@stevehora.com'
    ampElements = ["amp-accordion","amp-analytics", "amp-sidebar"] # AMP elements loaded on every page
    themeColor = "green" # Browser bar color
    googleanalytics = "UA-1341906-9"

# Where can we share?
[params.share]
    twitter = true
    pinterest = false
    facebook = true
	linkedin = true
	email = true

[params.favicon]
    manifest = "manifest.json"
    basename = "favicon"
    ms_tilecolor = "#FFFFFF"
    icon = [16, 32, 96, 192]
    apple_touch = [57, 60, 72, 76, 114, 120, 144, 152, 180]
    ms = [144]
    ms_config = "browserconfig.xml"

[[menu.main]]
    name = 'Home'
    weight = 1
    url = '/'

[[menu.main]]
    name = 'Free Vedic Chart'
    weight = 2
    url = '/vedic-chart/'

[[menu.main]]
    name = 'Steve Hora'
    weight = 3
    url = '/steve-hora/'

[[menu.main]]
    name = 'Articles'
    weight = 4
    url = '/articles/'
	
[[menu.main]]
    name = 'About Us'
    weight = 5
    url = '/about/'	
	
[[menu.main]]
    name = 'Contact Us'
    weight = 6
    url = '/contact/'	
	
#[[menu.main]]
#    name = 'Search'
#    weight = 7
#    url = '/search/'