[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  bundle = true
  minify = true

[build.processing.images]
  compress = true
  bundle = true
  minify = true
  
[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
	X-Content-Type-Options = "nosniff"
    #Referrer-Policy = "origin"
    Feature-Policy = "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'none'; payment 'none';"
	Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
	#Content-Security-Policy-Report-Only = "style-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com; script-src-elem 'self' 'unsafe-inline' markjs.io fusejs.io code.jquery.com google-analytics.com ajax.googleapis.com maxcdn.bootstrapcdn.com cdn.matomo.cloud https://www.google-analytics.com; script-src 'self' 'unsafe-inline' markjs.io fusejs.io code.jquery.com www.google-analytics.com ajax.googleapis.com maxcdn.bootstrapcdn.com  https://www.google-analytics.com; connect-src 'self' 'nonce-{SERVER-GENERATED-NONCE}'; img-src www.googletagmanager.com; font-src 'self' fonts.googleapis.com maxcdn.bootstrapcdn.com;"
 
#[[headers]]
#  for = "/*.*"
#  [headers.values]
#    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
